<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Zigote.UI.Material</RootNamespace>
        <AssemblyName>Zigote.UI.Material</AssemblyName>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Zigote.UI\Zigote.UI.csproj"/>
    </ItemGroup>
</Project>
