using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Zigote.Generators;

[Generator]
public class ZigoteBindingGenerator : IIncrementalGenerator
{
    // Entry points that get [SuppressGCTransition]: the runtime skips the cooperative→preemptive GC
    // transition (the dominant per-call P/Invoke cost) for these. ONLY safe for tiny, non-blocking,
    // leaf calls that write a few fields and return immediately — no GPU submit/present, no file IO,
    // no event polling, no managed callback, no unbounded copy. These per-node/per-frame setters
    // qualify; render/submit/poll/load entry points deliberately do NOT (they can block, and
    // suppressing the transition would stall the GC for the whole call).
    private static readonly HashSet<string> SuppressGcTransition = new(StringComparer.Ordinal) {
        "zigote_scene_update_node",
        "zigote_scene_set_node_visible",
        "zigote_scene_set_mesh_color",
        "zigote_scene_set_mesh_roughness",
        "zigote_scene_set_mesh_surface",
        "zigote_scene_set_mesh_emissive",
        "zigote_scene_set_mesh_effect",
        "zigote_scene_set_mesh_alpha_mode",
        "zigote_scene_set_mesh_double_sided",
        "zigote_scene_set_mesh_volume",
        "zigote_scene_set_mesh_occlusion_strength",
        "zigote_scene_set_light_properties",
        "zigote_scene_set_selected_node",
        "zigote_render_set_frustum_cull",
    };

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Ingest every `src/ffi/*.zig` file, not just root.zig, so each subsystem's `export fn`
        // ABI can live alongside its implementation (ecs.zig / physics.zig / audio.zig / …).
        var zigFiles = context.AdditionalTextsProvider
            .Where(static file =>
                {
                    var p = file.Path.Replace('\\', '/');
                    return p.EndsWith(".zig") && p.Contains("/ffi/");
                }
            )
            .Select(static (file, cancellationToken) =>
                {
                    var text = file.GetText(cancellationToken);
                    return (Path: file.Path.Replace('\\', '/'),
                        Text: text?.ToString() ?? string.Empty);
                }
            )
            .Collect();

        context.RegisterSourceOutput(
            zigFiles,
            static (spc, files) =>
            {
                // Deterministic order (path-sorted) so the generated output is stable across builds.
                var ordered = files
                    .Where(static f => !string.IsNullOrEmpty(f.Text))
                    .OrderBy(static f => f.Path, StringComparer.Ordinal);

                var source = GenerateBindings(ordered);
                if (source is null) return;
                spc.AddSource("NativeEngine.g.cs", SourceText.From(source, Encoding.UTF8));
            }
        );
    }

    private static string? GenerateBindings(IEnumerable<(string Path, string Text)> files)
    {
        // Concatenate exports across files, first-wins dedup by entry point (an entry point must be
        // unique in the shared lib, so a duplicate would only ever be an authoring mistake).
        var functions = new List<ZigFunction>();
        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (var (_, text) in files)
        foreach (var fn in ParseZigFunctions(text))
            if (seen.Add(fn.EntryPoint))
                functions.Add(fn);

        if (functions.Count == 0) return null;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated from src/ffi/*.zig — do not edit.");
        sb.AppendLine("// [DllImport] is used here intentionally: [LibraryImport] partial methods");
        sb.AppendLine(
            "// require the SDK LibraryImportGenerator which cannot process generator output."
        );
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine();
        sb.AppendLine("namespace Zigote.Core.Native;");
        sb.AppendLine();
        sb.AppendLine(
            "#pragma warning disable SYSLIB1054 // Use LibraryImportAttribute instead of DllImportAttribute"
        );
        sb.AppendLine("internal static unsafe partial class NativeEngine");
        sb.AppendLine("{");

        foreach (var func in functions)
        {
            sb.AppendLine($"    [DllImport(Lib, EntryPoint = \"{func.EntryPoint}\")]");
            if (SuppressGcTransition.Contains(func.EntryPoint))
                sb.AppendLine("    [SuppressGCTransition]");
            if (func.ReturnType == "bool")
                sb.AppendLine("    [return: MarshalAs(UnmanagedType.U1)]");

            sb.Append($"    {func.Visibility} static extern {func.ReturnType} {func.Name}(");

            for (var i = 0; i < func.Parameters.Count; i++)
            {
                var param = func.Parameters[i];
                sb.Append($"{param.Type} {param.Name}");
                if (i < func.Parameters.Count - 1) sb.Append(", ");
            }

            sb.AppendLine(");");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        sb.AppendLine("#pragma warning restore SYSLIB1054");
        return sb.ToString();
    }

    private static List<ZigFunction> ParseZigFunctions(string source)
    {
        var functions = new List<ZigFunction>();
        var index = 0;

        while (true)
        {
            index = source.IndexOf("export fn ", index);
            if (index == -1) break;

            // Skip a match that sits inside a line/doc comment (`//` … `///`) — with multiple files
            // ingested, the odds of "export fn" appearing in prose rise, and it must not emit a binding.
            var lineStart = source.LastIndexOf('\n', index) + 1;
            if (source.Substring(lineStart, index - lineStart).TrimStart().StartsWith("//"))
            {
                index += "export fn ".Length;
                continue;
            }

            index += "export fn ".Length;

            var openParen = source.IndexOf("(", index);
            if (openParen == -1) break;

            var fnName = source.Substring(index, openParen - index).Trim();

            var depth = 1;
            var closeParen = -1;
            for (var i = openParen + 1; i < source.Length; i++)
                if (source[i] == '(')
                {
                    depth++;
                }
                else if (source[i] == ')')
                {
                    depth--;
                    if (depth == 0)
                    {
                        closeParen = i;
                        break;
                    }
                }

            if (closeParen == -1) break;

            var paramsStr = source.Substring(openParen + 1, closeParen - openParen - 1);

            var nextBrace = source.IndexOf("{", closeParen);
            if (nextBrace == -1) break;

            var returnTypeStr = source.Substring(closeParen + 1, nextBrace - closeParen - 1).Trim();

            var func = new ZigFunction();
            func.EntryPoint = fnName;

            var stripped = fnName.StartsWith("zigote_") ? fnName.Substring(7) : fnName;
            func.Name = SnakeToPascal(stripped);
            func.Visibility = "public";

            func.ReturnType = MapZigTypeToCSharp("", returnTypeStr);

            var paramSegments = SplitParameters(paramsStr);
            foreach (var segment in paramSegments)
            {
                var colonIdx = segment.IndexOf(':');
                if (colonIdx == -1) continue;

                var paramName = segment.Substring(0, colonIdx).Trim();
                var paramType = segment.Substring(colonIdx + 1).Trim();

                var csharpName = SnakeToCamel(paramName);
                var csharpType = MapZigTypeToCSharp(paramName, paramType);

                func.Parameters.Add(
                    new ZigParameter {
                        Name = csharpName,
                        Type = csharpType,
                    }
                );
            }

            functions.Add(func);
            index = nextBrace + 1;
        }

        return functions;
    }

    private static List<string> SplitParameters(string paramsStr)
    {
        var list = new List<string>();
        var sb = new StringBuilder();
        var depth = 0;
        for (var i = 0; i < paramsStr.Length; i++)
        {
            var c = paramsStr[i];
            if (c == '(') depth++;
            else if (c == ')') depth--;

            if (c == ',' && depth == 0)
            {
                var p = sb.ToString().Trim();
                if (!string.IsNullOrEmpty(p)) list.Add(p);
                sb.Clear();
            }
            else
            {
                sb.Append(c);
            }
        }

        var last = sb.ToString().Trim();
        if (!string.IsNullOrEmpty(last)) list.Add(last);
        return list;
    }

    private static string MapZigTypeToCSharp(string paramName, string zigType)
    {
        zigType = zigType.Trim();

        if (zigType.Contains("fn") && zigType.Contains("callconv"))
            return MapFnPointer(zigType);

        if (zigType.StartsWith("[*c]const ") || zigType.StartsWith("[*]const "))
        {
            var innerType = zigType.Substring(zigType.IndexOf("const ") + 6).Trim();
            return MapSingleZigTypeToCSharp(innerType) + "*";
        }

        if (zigType.StartsWith("[*c]") || zigType.StartsWith("[*]"))
        {
            var innerType = zigType.Substring(zigType.IndexOf("]") + 1).Trim();
            return MapSingleZigTypeToCSharp(innerType) + "*";
        }

        if (zigType.StartsWith("*"))
        {
            var innerType = zigType.Substring(1).Trim();
            var csharpInnerType = MapSingleZigTypeToCSharp(innerType);
            if (paramName.StartsWith("out_")) return "out " + csharpInnerType;
            return csharpInnerType + "*";
        }

        return MapSingleZigTypeToCSharp(zigType);
    }

    /// <summary>
    ///     Map a Zig C-callconv function-pointer type (e.g. <c>?*const fn (u32, u32, u32) callconv(.c)
    ///     void</c>) to a C# unmanaged function pointer <c>delegate* unmanaged[Cdecl]&lt;…&gt;</c>, parsing
    ///     the real parameter and return types rather than assuming a fixed shape.
    /// </summary>
    private static string MapFnPointer(string zigType)
    {
        var fnIdx = zigType.IndexOf("fn", StringComparison.Ordinal);
        var open = fnIdx >= 0 ? zigType.IndexOf('(', fnIdx) : -1;
        if (open < 0) return "delegate* unmanaged[Cdecl]<int, byte*, void>"; // defensive fallback

        var close = MatchingParen(zigType, open);
        var paramsStr = zigType.Substring(open + 1, close - open - 1);

        // Return type follows the callconv(...) clause.
        var retType = "void";
        var ccIdx = zigType.IndexOf("callconv", close, StringComparison.Ordinal);
        if (ccIdx >= 0)
        {
            var ccOpen = zigType.IndexOf('(', ccIdx);
            var ccClose = MatchingParen(zigType, ccOpen);
            retType = zigType.Substring(ccClose + 1).Trim();
        }

        var args = new List<string>();
        foreach (var p in SplitParameters(paramsStr))
        {
            // A parameter may be "name: type" or a bare "type".
            var t = p;
            var colon = p.IndexOf(':');
            if (colon >= 0) t = p.Substring(colon + 1).Trim();
            args.Add(MapZigTypeToCSharp("", t));
        }

        args.Add(retType is "void" or "" ? "void" : MapSingleZigTypeToCSharp(retType));
        return "delegate* unmanaged[Cdecl]<" + string.Join(", ", args) + ">";
    }

    /// <summary>Index of the ')' matching the '(' at <paramref name="open" /> (nesting-aware).</summary>
    private static int MatchingParen(string s, int open)
    {
        var depth = 0;
        for (var i = open; i < s.Length; i++)
            if (s[i] == '(')
            {
                depth++;
            }
            else if (s[i] == ')')
            {
                depth--;
                if (depth == 0) return i;
            }

        return s.Length - 1;
    }

    private static string MapSingleZigTypeToCSharp(string zigType)
    {
        return zigType switch {
            "u8" => "byte",
            "u16" => "ushort",
            "u32" => "uint",
            "u64" => "ulong",
            "i32" => "int",
            "f32" => "float",
            "usize" => "nuint",
            "bool" => "bool",
            "void" => "void",
            "ZgResult" => "ZgResult",
            _ => zigType,
        };
    }

    private static string SnakeToCamel(string snake)
    {
        if (string.IsNullOrEmpty(snake)) return snake;
        var parts = snake.Split('_');
        var sb = new StringBuilder();
        sb.Append(parts[0]);
        for (var i = 1; i < parts.Length; i++)
            if (parts[i].Length > 0)
            {
                sb.Append(char.ToUpperInvariant(parts[i][0]));
                sb.Append(parts[i].AsSpan(1));
            }

        return sb.ToString();
    }

    private static string SnakeToPascal(string snake)
    {
        if (string.IsNullOrEmpty(snake)) return snake;
        var parts = snake.Split('_');
        var sb = new StringBuilder();
        foreach (var part in parts)
            if (part.Length > 0)
            {
                if (part.Equals("3d", StringComparison.OrdinalIgnoreCase))
                {
                    sb.Append("3D");
                }
                else
                {
                    sb.Append(char.ToUpperInvariant(part[0]));
                    sb.Append(part.AsSpan(1));
                }
            }

        return sb.ToString();
    }

    private class ZigFunction
    {
        public string EntryPoint { get; set; } = string.Empty;
        public string Name { get; set; } = string.Empty;
        public string ReturnType { get; set; } = string.Empty;
        public string Visibility { get; set; } = "public";
        public List<ZigParameter> Parameters { get; } = [];
    }

    private class ZigParameter
    {
        public string Name { get; set; } = string.Empty;
        public string Type { get; set; } = string.Empty;
    }
}