using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Zigote.Http.Generators;

/// <summary>
///     Turns <c>[HttpApi]</c> interfaces into sealed client classes at compile time. Retrofit's
///     surface, none of its reflection: the binding is code, the diagnostics are build errors, and
///     the result is trim- and AOT-clean.
/// </summary>
/// <remarks>
///     <para>
///         The design doc also called for a generated <c>JsonSerializerContext</c>. That cannot
///         work: source generators do not see each other's output, so <c>[JsonSerializable]</c>
///         attributes emitted here would never reach System.Text.Json's own generator. Instead a
///         generated client takes the app's context in its constructor and resolves
///         <c>JsonTypeInfo</c> from it — one small file the app writes once, and still no
///         reflection.
///     </para>
/// </remarks>
[Generator]
public sealed class HttpApiGenerator : IIncrementalGenerator
{
    private const string Ns = "Zigote.Http";

    private static readonly DiagnosticDescriptor UnboundPlaceholder = new(
        "ZHTTP001", "Route placeholder is not bound",
        "Route '{0}' has no parameter bound to '{{{1}}}'", "Zigote.Http", DiagnosticSeverity.Error, true);

    private static readonly DiagnosticDescriptor DuplicateBinding = new(
        "ZHTTP002", "Route placeholder is bound twice",
        "Route '{0}' binds '{{{1}}}' more than once", "Zigote.Http", DiagnosticSeverity.Error, true);

    private static readonly DiagnosticDescriptor NonReplayableBody = new(
        "ZHTTP003", "Retryable request has a non-replayable body",
        "'{0}' sends a Stream body on a retryable verb, and a stream cannot be sent twice",
        "Zigote.Http", DiagnosticSeverity.Error, true);

    private static readonly DiagnosticDescriptor MissingVerb = new(
        "ZHTTP004", "Method has no verb attribute",
        "'{0}' is on an [HttpApi] interface but carries no verb attribute", "Zigote.Http",
        DiagnosticSeverity.Error, true);

    private static readonly DiagnosticDescriptor UnsupportedReturn = new(
        "ZHTTP005", "Unsupported return type",
        "'{0}' must return Task<T> or ValueTask<T> where T is HttpResult of a payload type, HttpResponse, byte[] or string",
        "Zigote.Http", DiagnosticSeverity.Error, true);

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var apis = context.SyntaxProvider.ForAttributeWithMetadataName(
            $"{Ns}.HttpApiAttribute",
            static (node, _) => node is Microsoft.CodeAnalysis.CSharp.Syntax.InterfaceDeclarationSyntax,
            static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol);

        context.RegisterSourceOutput(apis, Emit);
    }

    private static void Emit(SourceProductionContext context, INamedTypeSymbol api)
    {
        string basePath = "";
        foreach (var attribute in api.GetAttributes())
        {
            if (attribute.AttributeClass?.Name != "HttpApiAttribute") continue;
            foreach (var named in attribute.NamedArguments)
                if (named.Key == "BasePath" && named.Value.Value is string value)
                    basePath = value.Trim('/');
        }

        string interfaceName = api.Name;
        string className = (interfaceName.Length > 1 && interfaceName[0] == 'I' && char.IsUpper(interfaceName[1])
            ? interfaceName.Substring(1)
            : interfaceName) + "Client";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Zigote.Http;"); // the fluent transforms are extension methods
        sb.AppendLine();
        bool global = api.ContainingNamespace.IsGlobalNamespace;
        if (!global) sb.AppendLine($"namespace {api.ContainingNamespace.ToDisplayString()};").AppendLine();

        sb.AppendLine($"/// <summary>Generated client for <see cref=\"{interfaceName}\"/>.</summary>");
        sb.AppendLine($"{Accessibility(api)} sealed partial class {className} : {api.ToDisplayString()}");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly global::Zigote.Http.HttpRunner _runner;");
        sb.AppendLine("    private readonly global::System.Text.Json.Serialization.JsonSerializerContext? _json;");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>A client over <paramref name=\"runner\"/>. <paramref name=\"json\"/> supplies the contracts for any JSON payload on this interface.</summary>");
        sb.AppendLine($"    public {className}(global::Zigote.Http.HttpRunner runner, global::System.Text.Json.Serialization.JsonSerializerContext? json = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        _runner = runner;");
        sb.AppendLine("        _json = json;");
        sb.AppendLine("    }");

        foreach (var member in api.GetMembers())
        {
            if (member is not IMethodSymbol method || method.MethodKind != MethodKind.Ordinary) continue;
            EmitMethod(context, sb, method, basePath);
        }

        sb.AppendLine();
        sb.AppendLine("    private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<T> TypeInfo<T>()");
        sb.AppendLine("    {");
        sb.AppendLine("        var info = _json?.GetTypeInfo(typeof(T)) as global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<T>;");
        sb.AppendLine("        return info ?? throw new global::System.InvalidOperationException(");
        sb.AppendLine("            $\"No JsonTypeInfo for {typeof(T)}. Pass a JsonSerializerContext that declares [JsonSerializable(typeof({typeof(T).Name}))].\");");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource($"{className}.g.cs", sb.ToString());
    }

    private static void EmitMethod(
        SourceProductionContext context, StringBuilder sb, IMethodSymbol method, string basePath)
    {
        var verb = VerbOf(method, out string template);
        if (verb is null)
        {
            context.ReportDiagnostic(Diagnostic.Create(MissingVerb, Location(method), method.Name));
            return;
        }

        string route = basePath.Length == 0 ? template.TrimStart('/') : $"{basePath}/{template.TrimStart('/')}";
        var placeholders = Placeholders(template);

        // Bind parameters before writing anything: a diagnostic is worth more than half a method.
        var bindings = new List<string>();
        var loops = new List<string>(); // repeated query params, emitted after the chain
        var bound = new HashSet<string>(StringComparer.Ordinal);
        string? cancellation = null;
        bool hasStreamBody = false;

        foreach (var parameter in method.Parameters)
        {
            string name = parameter.Name;
            if (parameter.Type.ToDisplayString() == "System.Threading.CancellationToken")
            {
                cancellation = name;
                continue;
            }

            if (HasAttribute(parameter, "BodyAttribute"))
            {
                bindings.Add(BodyBinding(parameter, ref hasStreamBody));
                continue;
            }

            if (AttributeArgument(parameter, "HeaderAttribute") is { } headerName)
            {
                bindings.Add($".WithHeader(\"{headerName}\", {Text(parameter)})");
                continue;
            }

            if (placeholders.Contains(name) && !HasAttribute(parameter, "QueryAttribute"))
            {
                if (!bound.Add(name))
                {
                    context.ReportDiagnostic(Diagnostic.Create(DuplicateBinding, Location(method), route, name));
                    return;
                }

                bindings.Add($".Route(\"{name}\", {Text(parameter)})");
                continue;
            }

            string queryName = AttributeArgument(parameter, "QueryAttribute") ?? name;

            // A sequence parameter repeats the pair — ?tag=a&tag=b — which is what every query
            // API on earth means by "a list". Emitted as a loop after the chain.
            if (ElementType(parameter.Type) is { } element)
            {
                string guard = parameter.NullableAnnotation == NullableAnnotation.Annotated
                    ? $"if ({name} is not null) "
                    : "";
                loops.Add($"{guard}foreach (var v in {name}) " +
                          $"spec = spec.WithQuery(\"{queryName}\", {ElementText(element)});");
                continue;
            }

            bindings.Add(parameter.NullableAnnotation == NullableAnnotation.Annotated
                ? $".WithQueryIf(\"{queryName}\", {Text(parameter)})"
                : $".WithQuery(\"{queryName}\", {Text(parameter)})");
        }

        foreach (string placeholder in placeholders)
            if (!bound.Contains(placeholder))
            {
                context.ReportDiagnostic(Diagnostic.Create(UnboundPlaceholder, Location(method), route, placeholder));
                return;
            }

        bool idempotent = HasAttribute(method, "IdempotentAttribute");
        if (hasStreamBody && (idempotent || verb is "Put" or "Delete"))
        {
            context.ReportDiagnostic(Diagnostic.Create(NonReplayableBody, Location(method), method.Name));
            return;
        }

        if (HasAttribute(method, "NoCacheAttribute")) bindings.Add(".NoCache()");
        if (idempotent) bindings.Add(".Idempotent()");
        if (HasAttribute(method, "NoRetryAttribute")) bindings.Add(".NoRetry()");
        if (HasAttribute(method, "StreamingAttribute")) bindings.Add(".Streaming()");
        if (DeadlineSeconds(method) is { } seconds)
            bindings.Add($".Deadline(global::System.TimeSpan.FromSeconds({seconds.ToString(System.Globalization.CultureInfo.InvariantCulture)}))");

        if (!Unwrap(method.ReturnType, out var payload, out bool resultShaped))
        {
            context.ReportDiagnostic(Diagnostic.Create(UnsupportedReturn, Location(method), method.Name));
            return;
        }

        string call = CallFor(payload!, cancellation ?? "default");
        string signature = string.Join(", ", method.Parameters.Select(Declare));

        sb.AppendLine();
        sb.AppendLine($"    /// <inheritdoc />");
        sb.AppendLine($"    public async {method.ReturnType.ToDisplayString()} {method.Name}({signature})");
        sb.AppendLine("    {");
        sb.AppendLine($"        var spec = global::Zigote.Http.HttpRequest.{verb}(\"{route}\")");
        foreach (string binding in bindings) sb.AppendLine($"            {binding}");
        sb.AppendLine("            ;");
        foreach (string loop in loops) sb.AppendLine($"        {loop}");
        sb.AppendLine($"        var result = await _runner.{call}.ConfigureAwait(false);");
        sb.AppendLine(resultShaped ? "        return result;" : "        return result.Unwrap();");
        sb.AppendLine("    }");
    }

    private static string CallFor(ITypeSymbol payload, string ct) => payload.ToDisplayString() switch
    {
        "byte[]" => $"BytesAsync(spec, {ct})",
        "string" => $"TextAsync(spec, {ct})",
        "Zigote.Http.HttpResponse" => $"SendAsync(spec, {ct})",
        _ => $"JsonAsync(spec, TypeInfo<{payload.ToDisplayString()}>(), {ct})"
    };

    private static string BodyBinding(IParameterSymbol parameter, ref bool hasStreamBody)
    {
        string type = parameter.Type.ToDisplayString();
        switch (type)
        {
            case "byte[]":
                return $".WithBody(global::Zigote.Http.HttpBody.Bytes({parameter.Name}))";
            case "string":
                return $".WithBody(global::Zigote.Http.HttpBody.Text({parameter.Name}))";
            case "System.IO.Stream":
                hasStreamBody = true;
                return $".WithBody(global::Zigote.Http.HttpBody.Stream({parameter.Name}))";
            case "Zigote.Http.HttpBody":
                return $".WithBody({parameter.Name})";
            default:
                return $".WithJson({parameter.Name}, TypeInfo<{type}>())";
        }
    }

    /// <summary>The element type of a sequence parameter, or null for scalars, strings and byte[].</summary>
    private static ITypeSymbol? ElementType(ITypeSymbol type)
    {
        if (type.SpecialType == SpecialType.System_String) return null;
        if (type is IArrayTypeSymbol { ElementType.SpecialType: SpecialType.System_Byte }) return null;
        if (type is IArrayTypeSymbol array) return array.ElementType;

        foreach (var iface in type.AllInterfaces)
            if (iface.ConstructedFrom.ToDisplayString() == "System.Collections.Generic.IEnumerable<T>")
                return iface.TypeArguments[0];
        return null;
    }

    /// <summary>How one element of a repeated query parameter is written.</summary>
    private static string ElementText(ITypeSymbol element)
    {
        if (element.SpecialType == SpecialType.System_String) return "v";
        bool formattable = element.AllInterfaces.Any(i => i.ToDisplayString() == "System.IFormattable");
        return formattable
            ? "v.ToString(null, global::System.Globalization.CultureInfo.InvariantCulture)"
            : "v?.ToString() ?? string.Empty";
    }

    /// <summary>The [Deadline] budget in seconds, or null.</summary>
    private static double? DeadlineSeconds(IMethodSymbol method)
    {
        foreach (var attribute in method.GetAttributes())
            if (attribute.AttributeClass?.Name == "DeadlineAttribute" &&
                attribute.ConstructorArguments.Length > 0 &&
                attribute.ConstructorArguments[0].Value is double seconds)
                return seconds;
        return null;
    }

    /// <summary>How a route or query value is written. Strings pass through; everything else formats invariantly.</summary>
    private static string Text(IParameterSymbol parameter)
    {
        if (parameter.Type.SpecialType == SpecialType.System_String) return parameter.Name;

        bool formattable = parameter.Type.AllInterfaces.Any(i => i.ToDisplayString() == "System.IFormattable");
        return formattable
            ? $"{parameter.Name}.ToString(null, global::System.Globalization.CultureInfo.InvariantCulture)"
            : $"{parameter.Name}?.ToString() ?? string.Empty";
    }

    /// <summary>Peels <c>Task</c>/<c>ValueTask</c> and then <c>HttpResult</c> off the declared return type.</summary>
    private static bool Unwrap(ITypeSymbol returnType, out ITypeSymbol? payload, out bool resultShaped)
    {
        payload = null;
        resultShaped = false;

        if (returnType is not INamedTypeSymbol named || named.TypeArguments.Length != 1) return false;
        string outer = named.ConstructedFrom.ToDisplayString();
        if (outer is not ("System.Threading.Tasks.Task<TResult>" or "System.Threading.Tasks.ValueTask<TResult>"))
            return false;

        var inner = named.TypeArguments[0];
        if (inner is INamedTypeSymbol result &&
            result.ConstructedFrom.ToDisplayString() == "Zigote.Http.HttpResult<T>")
        {
            resultShaped = true;
            payload = result.TypeArguments[0];
        }
        else
        {
            payload = inner;
        }

        // Stream is refused on purpose: who closes it, and what happens when the deadline fires
        // mid-read, are questions HttpResponse answers and a bare Stream does not.
        return payload.ToDisplayString() != "System.IO.Stream";
    }

    private static string Declare(IParameterSymbol parameter)
    {
        string declaration = $"{parameter.Type.ToDisplayString()} {parameter.Name}";
        return parameter.HasExplicitDefaultValue && parameter.ExplicitDefaultValue is null
            ? declaration + " = default"
            : declaration;
    }

    private static string? VerbOf(IMethodSymbol method, out string template)
    {
        template = "";
        foreach (var attribute in method.GetAttributes())
        {
            string? name = attribute.AttributeClass?.Name;
            string? verb = name switch
            {
                "GetAttribute" => "Get",
                "HeadAttribute" => "Head",
                "PostAttribute" => "Post",
                "PutAttribute" => "Put",
                "PatchAttribute" => "Patch",
                "DeleteAttribute" => "Delete",
                _ => null
            };
            if (verb is null) continue;
            if (attribute.ConstructorArguments.Length > 0 && attribute.ConstructorArguments[0].Value is string t)
                template = t;
            return verb;
        }

        return null;
    }

    private static HashSet<string> Placeholders(string template)
    {
        var names = new HashSet<string>(StringComparer.Ordinal);
        for (int i = 0; i < template.Length;)
        {
            int open = template.IndexOf('{', i);
            if (open < 0) break;
            int close = template.IndexOf('}', open);
            if (close < 0) break;
            names.Add(template.Substring(open + 1, close - open - 1));
            i = close + 1;
        }

        return names;
    }

    private static bool HasAttribute(ISymbol symbol, string name)
    {
        foreach (var attribute in symbol.GetAttributes())
            if (attribute.AttributeClass?.Name == name)
                return true;
        return false;
    }

    private static string? AttributeArgument(ISymbol symbol, string name)
    {
        foreach (var attribute in symbol.GetAttributes())
        {
            if (attribute.AttributeClass?.Name != name) continue;
            if (attribute.ConstructorArguments.Length > 0 && attribute.ConstructorArguments[0].Value is string value)
                return value;
            return null;
        }

        return null;
    }

    private static string Accessibility(INamedTypeSymbol api) =>
        api.DeclaredAccessibility == Microsoft.CodeAnalysis.Accessibility.Public ? "public" : "internal";

    private static Location? Location(ISymbol symbol) =>
        symbol.Locations.Length > 0 ? symbol.Locations[0] : null;
}
