<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Tests.fs"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.7.0"/>
        <PackageReference Include="xunit" Version="2.9.3"/>
        <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0-pre.4">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Update="FSharp.Core" Version="11.0.101-preview5.26302.115"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Zigote.UI.FSharp\Zigote.UI.FSharp.fsproj"/>
        <ProjectReference Include="..\Zigote.UI\Zigote.UI.csproj"/>
        <ProjectReference Include="..\Zigote.UI.Material\Zigote.UI.Material.csproj"/>
        <ProjectReference Include="..\Zigote.Core\Zigote.Core.csproj"/>
    </ItemGroup>

</Project>
