using System.Reflection;
using System.Text;
using Zigote.UI.Widgets;

namespace Zigote.UI.FSharp.Codegen;

/// <summary>
///     Emits the F# attr DSL from <see cref="WidgetSpecs" /> and validates the spec against the live
///     compiled widget types (drift + coverage). See the .csproj header for the reliability model.
/// </summary>
public static class AttrsGenerator
{
    private const string Header =
        """
        // <auto-generated>
        //     Generated by Zigote.UI.FSharp.Codegen from the widget spec (Codegen/Spec.cs), validated
        //     against the compiled Zigote.UI / Zigote.UI.Material assemblies. DO NOT EDIT BY HAND.
        //     Regenerate: dotnet run --project Zigote.UI.FSharp.Codegen -- Zigote.UI.FSharp/Attrs.g.fs
        // </auto-generated>
        namespace Zigote.UI.FSharp

        open System
        open Zigote.Core
        open Zigote.Core.Paint
        open Zigote.UI.Theme
        open Zigote.UI.Widgets
        open Zigote.UI.Widgets.Controls
        open Zigote.UI.Widgets.Layout
        open Zigote.UI.Material
        """;

    // Framework plumbing that must never become an attr.
    private static readonly HashSet<string> Framework = new() {
        "Parent",
        "Owner",
        "Key",
        "NeedsBuild",
        "NeedsLayout",
        "NeedsPaint",
        "Bounds",
        "MeasuredSize",
        "MeasureCount",
        "LayoutCount",
        "PaintCount",
        "RebuildCount",
        "Focused",
        "ScrollParent",
        "SemanticsId",
    };

    /// <summary>The canonical generated text (LF line endings), for the emitter and the staleness test.</summary>
    public static string Generate()
    {
        Validate(); // fail fast on a structurally-invalid spec before emitting
        var sb = new StringBuilder();
        sb.Append(Header.Replace("\r\n", "\n"));
        sb.Append('\n');

        foreach (var w in WidgetSpecs.All())
        {
            sb.Append('\n');
            sb.Append("[<RequireQualifiedAccess>]\n");
            sb.Append($"module {w.Module} =\n");
            for (var i = 0; i < w.Attrs.Count; i++)
            {
                sb.Append(EmitAttr(w, w.Attrs[i]));
                sb.Append('\n');
            }
        }

        return sb.ToString();
    }

    // ── emit one attr ────────────────────────────────────────────────────────

    private static string EmitAttr(WidgetSpec w, AttrSpec a)
    {
        if (a.Kind == AttrKind.Raw)
            return "    " + a.Raw;

        var prop = a.Prop!;
        var wt = w.WidgetType;
        var nullable = Nullable.GetUnderlyingType(prop.PropertyType) != null;

        string SetFrom(string token, bool rebuild)
        {
            var rhs = nullable ? $"Nullable {token}" : token;
            var s = $"w.{prop.Name} <- {rhs}";
            return rebuild ? s + "; w.MarkNeedsBuild()" : s;
        }

        var mk = a.Unset.Kind == UnsetKind.None ? "mkAttr" : "mkAttrReset";
        var reset = "";
        if (a.Unset.Kind != UnsetKind.None)
        {
            var rhs = a.Unset.Kind == UnsetKind.Nullable ? "Nullable()" : a.Unset.Expr!;
            var s = $"w.{prop.Name} <- {rhs}";
            if (a.Rebuild) s += "; w.MarkNeedsBuild()";
            reset = $" (fun w -> {s})";
        }

        switch (a.Kind)
        {
            case AttrKind.Param:
                return
                    $"    let {a.Member} (v: {FSharpType(prop.PropertyType)}) =\n" +
                    $"        {mk} \"{a.Member}\" v (fun (w: {wt}) x -> {SetFrom("x", a.Rebuild)}){reset}";

            case AttrKind.Fixed:
                return
                    $"    let {a.Member} =\n" +
                    $"        {mk} \"{a.Member}\" {a.FixedLiteral} (fun (w: {wt}) x -> {SetFrom("x", a.Rebuild)}){reset}";

            case AttrKind.Handler:
                // Reset to null so a conditionally-applied handler clears when it disappears (a stale
                // delegate would otherwise keep firing). The handler property is a nullable Action/Action<T>.
                return
                    $"    let {a.Member} (handler: {FSharpType(prop.PropertyType)}) =\n" +
                    $"        mkAttrReset \"{a.Member}\" handler (fun (w: {wt}) f -> w.{prop.Name} <- {ActionCtor(prop.PropertyType)}(f)) (fun w -> w.{prop.Name} <- null)";

            default:
                throw new InvalidOperationException($"unhandled attr kind {a.Kind}");
        }
    }

    /// <summary>
    ///     CLR type → the F# value type the attr exposes (unwraps Nullable, maps Action to a
    ///     function).
    /// </summary>
    private static string FSharpType(Type t)
    {
        var u = Nullable.GetUnderlyingType(t);
        if (u != null) t = u;

        if (t == typeof(float)) return "float32";
        if (t == typeof(double)) return "float";
        if (t == typeof(int)) return "int";
        if (t == typeof(bool)) return "bool";
        if (t == typeof(string)) return "string";
        if (t == typeof(Action)) return "unit -> unit";
        if (t.IsGenericType && t.GetGenericTypeDefinition() == typeof(Action<>))
            return FSharpType(t.GetGenericArguments()[0]) + " -> unit";
        if (t.IsNested)
        {
            // A nested type on a GENERIC widget (e.g. Dropdown<T>.Foo) would emit a backtick-mangled
            // `Dropdown`1.Foo` — no current attr hits this; fail loud rather than emit garbage.
            if (t.DeclaringType!.IsGenericType)
                throw new NotSupportedException(
                    $"nested type on a generic widget is unsupported: {t}"
                );
            return t.DeclaringType.Name + "." + t.Name; // Label.LabelStyle
        }

        return t.Name; // Color, EdgeInsets, ShadowStyle, enums, Alignment…
    }

    /// <summary>
    ///     The F# constructor expression for an <c>Action</c>/<c>Action&lt;T&gt;</c> handler
    ///     property.
    /// </summary>
    private static string ActionCtor(Type t)
    {
        if (t == typeof(Action)) return "Action";
        if (t.IsGenericType && t.GetGenericTypeDefinition() == typeof(Action<>))
            return $"Action<{FSharpType(t.GetGenericArguments()[0])}>";
        throw new InvalidOperationException($"handler property is not an Action: {t}");
    }

    // ── validation / coverage (the reliability legs) ─────────────────────────

    /// <summary>
    ///     Hard structural assertions against the live types — throws (fails generation) on violation:
    ///     every referenced property is settable, and a <c>StatelessWidget</c> that does not
    ///     self-invalidate has <c>rebuild: true</c> on every attr (else a re-render is silently dropped,
    ///     the divider-class bug). Semantic correctness of Unset defaults is NOT verifiable from types —
    ///     that is the behavioral tests' job (a generator can't derive it).
    /// </summary>
    public static void Validate()
    {
        foreach (var w in WidgetSpecs.All())
        {
            foreach (var a in w.Attrs)
                if (a.Prop is { CanWrite: false })
                    throw new InvalidOperationException(
                        $"{w.Module}.{a.Member}: property {w.Clr.Name}.{a.Prop.Name} has no setter"
                    );

            // A StatelessWidget reads its props in Build(); the reconciler only MarkNeedsLayout, which
            // does NOT re-run Build unless the setter self-invalidates. So every value attr must rebuild.
            if (typeof(StatelessWidget).IsAssignableFrom(w.Clr) && !w.SelfInvalidating)
                foreach (var a in w.Attrs)
                    if ((a.Kind == AttrKind.Param || a.Kind == AttrKind.Fixed) && !a.Rebuild)
                        throw new InvalidOperationException(
                            $"{w.Module}.{a.Member}: {w.Clr.Name} is a StatelessWidget that does not self-invalidate — " +
                            $"the attr needs rebuild:true (or mark the widget .SelfInvalidating() if its setters call Invalidate())."
                        );
        }
    }

    /// <summary>
    ///     Report public settable instance properties with no attr, minus framework plumbing and the
    ///     spec's declared <see cref="WidgetSpec.Structural" /> (positional-ctor) props — so the residual
    ///     is only real candidates for new attrs. Informational; never fails the build.
    /// </summary>
    public static string Coverage()
    {
        var report = new StringBuilder();
        foreach (var w in WidgetSpecs.All())
        {
            var covered = w.Attrs.Where(a => a.Prop is not null).Select(a => a.Prop!.Name)
                .ToHashSet();

            var candidates = w.Clr
                .GetProperties(BindingFlags.Public | BindingFlags.Instance)
                .Where(p =>
                    p.CanWrite && p.SetMethod!.IsPublic && p.GetIndexParameters().Length == 0
                )
                .Select(p => p.Name)
                .Where(n =>
                    !Framework.Contains(n) && !w.Structural.Contains(n) && !covered.Contains(n)
                )
                .OrderBy(n => n)
                .ToList();

            if (candidates.Count > 0)
                report.Append($"  {w.Module} ({w.Clr.Name}): {string.Join(", ", candidates)}\n");
        }

        return report.ToString();
    }

    // ── entry point ──────────────────────────────────────────────────────────

    public static int Main(string[] args)
    {
        var check = args.Contains("--check");
        var outPath = args.FirstOrDefault(a => !a.StartsWith("--"));

        string text;
        try
        {
            text = Generate(); // validates the spec (throws on a structural violation)
        }
        catch (InvalidOperationException e)
        {
            // A structurally-invalid spec — surface a clean nonzero exit (not an uncaught-exception
            // crash) so the build-time --check gate reports it, not a 134.
            Console.Error.WriteLine($"Spec validation failed: {e.Message}");
            return 3;
        }

        var coverage = Coverage();
        if (coverage.Length > 0)
        {
            Console.WriteLine(
                "Coverage (settable widget properties with no F# attr — candidates for new attrs):"
            );
            Console.Write(coverage);
        }
        else
        {
            Console.WriteLine(
                "Coverage: every non-structural settable widget property is covered."
            );
        }

        if (check)
        {
            if (outPath is null)
            {
                Console.Error.WriteLine("--check needs a file path to compare against");
                return 2;
            }

            var current = File.Exists(outPath)
                ? File.ReadAllText(outPath).Replace("\r\n", "\n")
                : "";
            if (current == text)
            {
                Console.WriteLine($"{outPath} is up to date.");
                return 0;
            }

            Console.Error.WriteLine($"{outPath} is STALE — regenerate with the tool (no --check).");
            return 1;
        }

        if (outPath is null)
        {
            Console.Write(text);
            return 0;
        }

        File.WriteAllText(outPath, text);
        Console.WriteLine(
            $"Wrote {outPath} ({WidgetSpecs.All().Sum(w => w.Attrs.Count)} attrs across {WidgetSpecs.All().Count} modules)."
        );
        return 0;
    }
}