<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>Zigote.Modules.UI.CodeEditor</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Highlighting.fs"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="XParsec" Version="1.0.0"/>
        <PackageReference Update="FSharp.Core" Version="10.1.400" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Zigote.UI\Zigote.UI.csproj"/>
    </ItemGroup>

</Project>
