namespace Zigote.Core.Native;

/// <summary>
///     Raw P/Invoke bindings to libzigote.
///     All method declarations are auto-generated by ZigoteBindingGenerator from src/ffi/root.zig.
///     Use <see cref="Zigote.Core.Engine.ZigoteEngine" /> for the high-level API.
/// </summary>
internal static partial class NativeEngine
{
    private const string Lib = "zigote";
}