namespace Zigote.Core.Native;

/// <summary>
///     Raw P/Invoke bindings to libzigote.
///     All method declarations are auto-generated by ZigoteBindingGenerator from src/ffi/root.zig.
///     Use <see cref="Zigote.Core.Engine.ZigoteEngine" /> for the high-level API.
/// </summary>
internal static partial class NativeEngine
{
#if ZIGOTE_STATIC_NATIVE
    // iOS (and any statically-linked host): the engine is linked into the executable itself —
    // dynamic library loading is prohibited there — and "__Internal" tells the runtime to
    // resolve the symbols from the main binary. Defined by the mobile publish profile.
    private const string Lib = "__Internal";
#else
    private const string Lib = "zigote";
#endif
}