<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Zigote.Logging</RootNamespace>
        <AssemblyName>Zigote.Logging</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Zigote.Core\Zigote.Core.csproj"/>
        <ProjectReference Include="..\Zigote.Bloc\Zigote.Bloc.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Serilog" Version="4.4.0"/>
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1"/>
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0"/>
    </ItemGroup>
</Project>
