<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <OutputType>Exe</OutputType>
        <RootNamespace>Zigote.UI.Functional.Demo</RootNamespace>
        <AssemblyName>Zigote.UI.Functional.Demo</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Zigote.UI.Functional\Zigote.UI.Functional.csproj"/>
        <ProjectReference Include="..\Zigote.UI.Adwaita\Zigote.UI.Adwaita.csproj"/>
    </ItemGroup>

</Project>
