// <auto-generated>
//     Generated by Zigote.UI.FSharp.Codegen from the widget spec (Codegen/Spec.cs), validated
//     against the compiled Zigote.UI / Zigote.UI.Material assemblies. DO NOT EDIT BY HAND.
//     Regenerate: dotnet run --project Zigote.UI.FSharp.Codegen -- Zigote.UI.FSharp/Attrs.g.fs
// </auto-generated>
namespace Zigote.UI.FSharp

open System
open Zigote.Core
open Zigote.Core.Paint
open Zigote.UI.Theme
open Zigote.UI.Widgets
open Zigote.UI.Widgets.Controls
open Zigote.UI.Widgets.Layout
open Zigote.UI.Material

[<RequireQualifiedAccess>]
module text =
    let fontSize (v: float32) =
        mkAttrReset "fontSize" v (fun (w: Label) x -> w.FontSize <- Nullable x) (fun w -> w.FontSize <- Nullable())
    let color (v: Color) =
        mkAttrReset "color" v (fun (w: Label) x -> w.Color <- Nullable x) (fun w -> w.Color <- Nullable())
    let weight (v: FontWeight) =
        mkAttrReset "weight" v (fun (w: Label) x -> w.FontWeight <- x) (fun w -> w.FontWeight <- FontWeight.Normal)
    let italic =
        mkAttrReset "italic" FontStyle.Italic (fun (w: Label) x -> w.FontStyle <- x) (fun w -> w.FontStyle <- FontStyle.Normal)
    let align (v: TextAlign) =
        mkAttrReset "align" v (fun (w: Label) x -> w.Align <- x) (fun w -> w.Align <- TextAlign.Left)
    let style (v: Label.LabelStyle) =
        mkAttrReset "style" v (fun (w: Label) x -> w.Style <- x) (fun w -> w.Style <- Label.LabelStyle.Body)
    let maxLines (v: int) =
        mkAttrReset "maxLines" v (fun (w: Label) x -> w.MaxLines <- Nullable x) (fun w -> w.MaxLines <- Nullable())
    let ellipsis =
        mkAttrReset "ellipsis" TextOverflow.Ellipsis (fun (w: Label) x -> w.Overflow <- x) (fun w -> w.Overflow <- TextOverflow.Clip)
    let family (v: string) =
        mkAttrReset "family" v (fun (w: Label) x -> w.FontFamily <- x) (fun w -> w.FontFamily <- null)
    let lineHeight (v: float32) =
        mkAttrReset "lineHeight" v (fun (w: Label) x -> w.LineHeight <- Nullable x) (fun w -> w.LineHeight <- Nullable())
    let letterSpacing (v: float32) =
        mkAttrReset "letterSpacing" v (fun (w: Label) x -> w.LetterSpacing <- x) (fun w -> w.LetterSpacing <- 0f)
    let bold = weight FontWeight.Bold

[<RequireQualifiedAccess>]
module column =
    let mainAxis (v: MainAxisAlignment) =
        mkAttr "mainAxis" v (fun (w: Column) x -> w.MainAxisAlign <- x)
    let crossAxis (v: CrossAxisAlignment) =
        mkAttr "crossAxis" v (fun (w: Column) x -> w.CrossAxisAlign <- x)
    let mainAxisSize (v: MainAxisSize) =
        mkAttr "mainAxisSize" v (fun (w: Column) x -> w.MainAxisSize <- x)

[<RequireQualifiedAccess>]
module row =
    let mainAxis (v: MainAxisAlignment) =
        mkAttr "mainAxis" v (fun (w: Row) x -> w.MainAxisAlign <- x)
    let crossAxis (v: CrossAxisAlignment) =
        mkAttr "crossAxis" v (fun (w: Row) x -> w.CrossAxisAlign <- x)
    let mainAxisSize (v: MainAxisSize) =
        mkAttr "mainAxisSize" v (fun (w: Row) x -> w.MainAxisSize <- x)

[<RequireQualifiedAccess>]
module stack =
    let alignment (v: Alignment) =
        mkAttr "alignment" v (fun (w: Stack) x -> w.Alignment <- x)

[<RequireQualifiedAccess>]
module wrap =
    let spacing (v: float32) =
        mkAttr "spacing" v (fun (w: Wrap) x -> w.Spacing <- x)
    let runSpacing (v: float32) =
        mkAttr "runSpacing" v (fun (w: Wrap) x -> w.RunSpacing <- x)
    let vertical =
        mkAttr "vertical" Axis.Vertical (fun (w: Wrap) x -> w.Direction <- x)

[<RequireQualifiedAccess>]
module button =
    let style (v: ButtonStyle) =
        mkAttr "style" v (fun (w: Button) x -> w.Style <- x)
    let enabled (v: bool) =
        mkAttr "enabled" v (fun (w: Button) x -> w.Enabled <- x)
    let background (v: Color) =
        mkAttrReset "background" v (fun (w: Button) x -> w.BackgroundColor <- Nullable x; w.MarkNeedsBuild()) (fun w -> w.BackgroundColor <- Nullable(); w.MarkNeedsBuild())
    let textColor (v: Color) =
        mkAttrReset "textColor" v (fun (w: Button) x -> w.TextColor <- Nullable x; w.MarkNeedsBuild()) (fun w -> w.TextColor <- Nullable(); w.MarkNeedsBuild())
    let fontSize (v: float32) =
        mkAttrReset "fontSize" v (fun (w: Button) x -> w.FontSize <- Nullable x; w.MarkNeedsBuild()) (fun w -> w.FontSize <- Nullable(); w.MarkNeedsBuild())
    let radius (v: float32) =
        mkAttrReset "radius" v (fun (w: Button) x -> w.Radius <- Nullable x; w.MarkNeedsBuild()) (fun w -> w.Radius <- Nullable(); w.MarkNeedsBuild())
    let padding (v: EdgeInsets) =
        mkAttrReset "padding" v (fun (w: Button) x -> w.Padding <- Nullable x; w.MarkNeedsBuild()) (fun w -> w.Padding <- Nullable(); w.MarkNeedsBuild())
    let outlined = style ButtonStyle.Outlined
    let flat = style ButtonStyle.Flat

[<RequireQualifiedAccess>]
module textField =
    let hint (v: string) =
        mkAttr "hint" v (fun (w: TextField) x -> w.Hint <- x)
    let readOnly (v: bool) =
        mkAttr "readOnly" v (fun (w: TextField) x -> w.ReadOnly <- x)
    let obscure (v: bool) =
        mkAttr "obscure" v (fun (w: TextField) x -> w.Obscure <- x)
    let multiline =
        mkAttr "multiline" true (fun (w: TextField) x -> w.Multiline <- x)
    let minLines (v: int) =
        mkAttr "minLines" v (fun (w: TextField) x -> w.MinLines <- x)
    let maxLines (v: int) =
        mkAttr "maxLines" v (fun (w: TextField) x -> w.MaxLines <- x)
    let height (v: float32) =
        mkAttr "height" v (fun (w: TextField) x -> w.Height <- x)
    let minWidth (v: float32) =
        mkAttr "minWidth" v (fun (w: TextField) x -> w.MinWidth <- x)
    let onSubmit (handler: string -> unit) =
        mkAttrReset "onSubmit" handler (fun (w: TextField) f -> w.OnSubmit <- Action<string>(f)) (fun w -> w.OnSubmit <- null)

[<RequireQualifiedAccess>]
module slider =
    let min (v: float32) =
        mkAttr "min" v (fun (w: Slider) x -> w.Min <- x)
    let max (v: float32) =
        mkAttr "max" v (fun (w: Slider) x -> w.Max <- x)
    let enabled (v: bool) =
        mkAttr "enabled" v (fun (w: Slider) x -> w.Enabled <- x)
    let range (lo: float32) (hi: float32) = [ min lo; max hi ]

[<RequireQualifiedAccess>]
module scrollView =
    let horizontal =
        mkAttr "horizontal" true (fun (w: ScrollView) x -> w.ScrollHorizontal <- x)
    let noVertical =
        mkAttr "noVertical" false (fun (w: ScrollView) x -> w.ScrollVertical <- x)
    let smooth (v: bool) =
        mkAttr "smooth" v (fun (w: ScrollView) x -> w.Smooth <- x)

[<RequireQualifiedAccess>]
module decorated =
    let fill (v: Color) =
        mkAttrReset "fill" v (fun (w: DecoratedBox) x -> w.Fill <- x) (fun w -> w.Fill <- Color.Transparent)
    let radius (v: float32) =
        mkAttrReset "radius" v (fun (w: DecoratedBox) x -> w.Radius <- x) (fun w -> w.Radius <- 0f)
    let borderColor (v: Color) =
        mkAttrReset "borderColor" v (fun (w: DecoratedBox) x -> w.BorderColor <- x) (fun w -> w.BorderColor <- Color.Transparent)
    let borderWidth (v: float32) =
        mkAttrReset "borderWidth" v (fun (w: DecoratedBox) x -> w.BorderWidth <- x) (fun w -> w.BorderWidth <- 1f)
    let elevation (v: ShadowStyle) =
        mkAttrReset "elevation" v (fun (w: DecoratedBox) x -> w.Elevation <- Nullable x) (fun w -> w.Elevation <- Nullable())

[<RequireQualifiedAccess>]
module card =
    let padding (v: EdgeInsets) =
        mkAttrReset "padding" v (fun (w: Card) x -> w.Padding <- Nullable x) (fun w -> w.Padding <- Nullable())
    let radius (v: float32) =
        mkAttrReset "radius" v (fun (w: Card) x -> w.Radius <- Nullable x) (fun w -> w.Radius <- Nullable())
    let color (v: Color) =
        mkAttrReset "color" v (fun (w: Card) x -> w.Color <- Nullable x) (fun w -> w.Color <- Nullable())
    let bordered (v: bool) =
        mkAttr "bordered" v (fun (w: Card) x -> w.Bordered <- x)

[<RequireQualifiedAccess>]
module divider =
    let vertical =
        mkAttr "vertical" true (fun (w: Divider) x -> w.Vertical <- x; w.MarkNeedsBuild())
    let thickness (v: float32) =
        mkAttr "thickness" v (fun (w: Divider) x -> w.Thickness <- x; w.MarkNeedsBuild())
    let color (v: Color) =
        mkAttrReset "color" v (fun (w: Divider) x -> w.Color <- Nullable x; w.MarkNeedsBuild()) (fun w -> w.Color <- Nullable(); w.MarkNeedsBuild())

[<RequireQualifiedAccess>]
module dropdown =
    let height (v: float32) =
        mkAttr "height" v (fun (w: Dropdown<string>) x -> w.Height <- x)
    let minWidth (v: float32) =
        mkAttr "minWidth" v (fun (w: Dropdown<string>) x -> w.MinWidth <- x)
