// IconGen — icon-font (.ttf/.otf) → C# constants class generator.
//
// Reads an icon font's `cmap` (codepoint → glyph) and, when present, its `post` v2.0 table
// (glyph → name), and emits a static C# class of `public const string` entries — one per glyph,
// each the C#-escaped code unit ("") named after the glyph, in the style of Icons.cs.
//
// Fonts whose `post` table carries no names (Material Icons / Noto Emoji ship `post` v3.0) get
// their names from a `--codepoints` sidecar in the Material "name hex\n" format, or fall back to
// a `<prefix><HEX>` identifier.
//
// This is a .NET 10 file-based app — no project, no dependencies. Run it directly:
//
//   dotnet run tools/IconGen.cs -- <font.ttf> [options]
//
// Options:
//   -o, --out <path>          Output .cs file (default: stdout)
//   -n, --namespace <ns>      Namespace (default: Zigote.UI.Theme)
//   -c, --class <name>        Class name (default: derived from the font file name)
//   -f, --family <name>       Font-family string for the Family const (default: class name)
//       --codepoints <file>   Material-style "name hex" sidecar for glyph names (name source)
//       --pua-only            Only emit Private-Use-Area codepoints (icon glyphs; drops Latin/etc.)
//       --prefix <str>        Identifier prefix for unnamed glyphs (default: "Icon")
//       --no-family           Omit the Family constant (e.g. when merging into a partial class)
//       --limit <n>           Emit at most n glyphs (smoke-testing)
//
// Example (regenerate a Material Icons catalogue):
//   dotnet run tools/IconGen.cs -- Zigote.Editor/Fonts/MaterialIcons/MaterialIcons-Regular.ttf \
//       --codepoints MaterialIcons-Regular.codepoints --pua-only \
//       -c MaterialIconsCatalog -o Zigote.UI/Theme/MaterialIconsCatalog.g.cs

using System.Buffers.Binary;
using System.Globalization;
using System.Text;

var opts = IconGenOptions.Parse(args);
if (opts is null) return 1;

byte[] bytes;
try
{
    bytes = File.ReadAllBytes(opts.FontPath);
}
catch (Exception ex)
{
    Console.Error.WriteLine($"error: cannot read '{opts.FontPath}': {ex.Message}");
    return 1;
}

SfntFont font;
try
{
    font = SfntFont.Parse(bytes);
}
catch (Exception ex)
{
    Console.Error.WriteLine($"error: '{opts.FontPath}' is not a parseable sfnt font: {ex.Message}");
    return 1;
}

// Name source priority: sidecar codepoints file > post v2.0 names > <prefix><HEX> fallback.
Dictionary<int, string>? sidecar = null;
if (opts.CodepointsPath is not null)
{
    try
    {
        sidecar = Codepoints.Load(opts.CodepointsPath);
    }
    catch (Exception ex)
    {
        Console.Error.WriteLine($"error: cannot read codepoints '{opts.CodepointsPath}': {ex.Message}");
        return 1;
    }
}

var cmap = font.ReadCmap();
var postNames = font.ReadPostNames(); // gid -> name, empty when post is not v2.0

var entries = new List<IconEntry>(cmap.Count);
foreach (var (cp, gid) in cmap)
{
    if (gid == 0) continue;              // .notdef
    if (cp < 0x20) continue;             // controls
    if (opts.PuaOnly && !IsPrivateUse(cp)) continue;

    string? name =
        (sidecar is not null && sidecar.TryGetValue(cp, out var sn)) ? sn
        : (postNames.TryGetValue(gid, out var pn) ? pn : null);

    entries.Add(new IconEntry(cp, name));
}

entries.Sort(static (a, b) => a.Codepoint.CompareTo(b.Codepoint));
if (opts.Limit is { } lim && entries.Count > lim)
    entries = entries.GetRange(0, lim);

if (entries.Count == 0)
{
    Console.Error.WriteLine("error: no glyphs matched (font has no cmap entries, or --pua-only excluded them all)");
    return 1;
}

var src = Emit(entries, opts, Path.GetFileName(opts.FontPath));

if (opts.OutPath is null)
{
    Console.Out.Write(src);
}
else
{
    File.WriteAllText(opts.OutPath, src);
    var named = entries.Count(e => e.RawName is not null);
    Console.Error.WriteLine(
        $"wrote {entries.Count} icons ({named} named, {entries.Count - named} fallback) → {opts.OutPath}");
}

return 0;

static bool IsPrivateUse(int cp) =>
    (cp >= 0xE000 && cp <= 0xF8FF) ||       // BMP PUA
    (cp >= 0xF0000 && cp <= 0xFFFFD) ||     // Plane 15 PUA-A
    (cp >= 0x100000 && cp <= 0x10FFFD);     // Plane 16 PUA-B

static string Emit(List<IconEntry> entries, IconGenOptions o, string fontFile)
{
    var used = new HashSet<string>(StringComparer.Ordinal);
    var sb = new StringBuilder(entries.Count * 64);

    sb.Append("// <auto-generated>\n");
    sb.Append($"//     Generated by tools/IconGen.cs from {fontFile}.\n");
    sb.Append("//     Do not edit by hand — re-run IconGen to regenerate.\n");
    sb.Append("// </auto-generated>\n\n");
    sb.Append($"namespace {o.Namespace};\n\n");
    sb.Append("/// <summary>Icon glyph codepoints from the ").Append(o.Family)
      .Append(" face. Render each constant as text in the <c>Family</c> font.</summary>\n");
    sb.Append($"public static partial class {o.ClassName}\n{{\n");

    if (o.EmitFamily)
    {
        sb.Append("    /// <summary>Font family name this face is registered under.</summary>\n");
        sb.Append($"    public const string Family = {Quote(o.Family)};\n\n");
    }

    foreach (var e in entries)
    {
        var id = Identifiers.Make(e.RawName, e.Codepoint, o.Prefix, used);
        sb.Append("    public const string ").Append(id).Append(" = ")
          .Append(Escape(e.Codepoint)).Append(';');

        // Trailing comment: the source name and the U+ codepoint for cross-reference.
        sb.Append(" // ");
        if (e.RawName is not null) sb.Append(e.RawName).Append(' ');
        sb.Append("U+").Append(e.Codepoint.ToString("X4", CultureInfo.InvariantCulture));
        sb.Append('\n');
    }

    sb.Append("}\n");
    return sb.ToString();
}

// C# string literal holding a single code unit / code point.
static string Escape(int cp) =>
    cp <= 0xFFFF
        ? $"\"\\u{cp:X4}\""
        : $"\"\\U{cp:X8}\"";

static string Quote(string s) => "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

// ── Types ───────────────────────────────────────────────────────────────────────────────────

readonly record struct IconEntry(int Codepoint, string? RawName);

sealed class IconGenOptions
{
    public required string FontPath { get; init; }
    public string? OutPath { get; init; }
    public string Namespace { get; init; } = "Zigote.UI.Theme";
    public required string ClassName { get; init; }
    public required string Family { get; init; }
    public string? CodepointsPath { get; init; }
    public bool PuaOnly { get; init; }
    public string Prefix { get; init; } = "Icon";
    public bool EmitFamily { get; init; } = true;
    public int? Limit { get; init; }

    public static IconGenOptions? Parse(string[] args)
    {
        string? font = null, outp = null, ns = null, cls = null, family = null, cps = null, prefix = null;
        bool pua = false, noFamily = false;
        int? limit = null;

        for (var i = 0; i < args.Length; i++)
        {
            var a = args[i];
            string Next(string flag)
            {
                if (i + 1 >= args.Length) throw new ArgumentException($"{flag} needs a value");
                return args[++i];
            }

            switch (a)
            {
                case "-o" or "--out": outp = Next(a); break;
                case "-n" or "--namespace": ns = Next(a); break;
                case "-c" or "--class": cls = Next(a); break;
                case "-f" or "--family": family = Next(a); break;
                case "--codepoints": cps = Next(a); break;
                case "--pua-only": pua = true; break;
                case "--prefix": prefix = Next(a); break;
                case "--no-family": noFamily = true; break;
                case "--limit": limit = int.Parse(Next(a), CultureInfo.InvariantCulture); break;
                case "-h" or "--help": Usage(); return null;
                default:
                    if (a.StartsWith('-')) { Console.Error.WriteLine($"error: unknown option '{a}'"); return null; }
                    if (font is not null) { Console.Error.WriteLine("error: multiple font paths given"); return null; }
                    font = a;
                    break;
            }
        }

        if (font is null) { Usage(); return null; }

        var derived = DeriveClassName(font);
        return new IconGenOptions
        {
            FontPath = font,
            OutPath = outp,
            Namespace = ns ?? "Zigote.UI.Theme",
            ClassName = cls ?? derived,
            Family = family ?? cls ?? derived,
            CodepointsPath = cps,
            PuaOnly = pua,
            Prefix = prefix ?? "Icon",
            EmitFamily = !noFamily,
            Limit = limit,
        };
    }

    // "MaterialIcons-Regular.ttf" → "MaterialIcons"; strips a trailing "-Regular"/weight suffix.
    static string DeriveClassName(string path)
    {
        var stem = Path.GetFileNameWithoutExtension(path);
        var dash = stem.IndexOf('-');
        if (dash > 0) stem = stem[..dash];
        var id = Identifiers.Sanitize(stem);
        return string.IsNullOrEmpty(id) ? "Icons" : id;
    }

    static void Usage() => Console.Error.WriteLine(
        "usage: dotnet run tools/IconGen.cs -- <font.ttf> [-o out.cs] [-n namespace] [-c Class]\n" +
        "                    [-f Family] [--codepoints file] [--pua-only] [--prefix Icon]\n" +
        "                    [--no-family] [--limit n]");
}

static class Codepoints
{
    // Material Icons "codepoints" sidecar: one "name hex" pair per line.
    public static Dictionary<int, string> Load(string path)
    {
        var map = new Dictionary<int, string>();
        foreach (var raw in File.ReadLines(path))
        {
            var line = raw.Trim();
            if (line.Length == 0 || line[0] == '#') continue;
            var parts = line.Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries);
            if (parts.Length < 2) continue;
            if (int.TryParse(parts[1], NumberStyles.HexNumber, CultureInfo.InvariantCulture, out var cp))
                map[cp] = parts[0];
        }
        return map;
    }
}

static class Identifiers
{
    static readonly HashSet<string> Keywords = new(StringComparer.Ordinal)
    {
        "abstract","as","base","bool","break","byte","case","catch","char","checked","class","const",
        "continue","decimal","default","delegate","do","double","else","enum","event","explicit","extern",
        "false","finally","fixed","float","for","foreach","goto","if","implicit","in","int","interface",
        "internal","is","lock","long","namespace","new","null","object","operator","out","override","params",
        "private","protected","public","readonly","ref","return","sbyte","sealed","short","sizeof","stackalloc",
        "static","string","struct","switch","this","throw","true","try","typeof","uint","ulong","unchecked",
        "unsafe","ushort","using","virtual","void","volatile","while",
    };

    // Turn a glyph name (or fallback hex) into a unique, valid PascalCase C# identifier.
    public static string Make(string? rawName, int cp, string prefix, HashSet<string> used)
    {
        var id = rawName is not null ? Sanitize(rawName) : "";
        if (string.IsNullOrEmpty(id))
            id = prefix + cp.ToString("X4", CultureInfo.InvariantCulture);

        if (Keywords.Contains(id)) id = "@" + id;

        var candidate = id;
        var n = 2;
        while (!used.Add(candidate))
            candidate = $"{id}_{cp:X4}_{n++}"; // stable, collision-proof suffix
        return candidate;
    }

    // PascalCase, keeping only ASCII letters/digits; a leading digit gets an underscore.
    public static string Sanitize(string name)
    {
        var sb = new StringBuilder(name.Length);
        var upperNext = true;
        foreach (var ch in name)
        {
            if (ch is (>= 'a' and <= 'z') or (>= 'A' and <= 'Z') or (>= '0' and <= '9'))
            {
                sb.Append(upperNext ? char.ToUpperInvariant(ch) : ch);
                upperNext = false;
            }
            else
            {
                upperNext = true; // separator (_ - space . etc.) → camel boundary
            }
        }

        if (sb.Length == 0) return "";
        if (char.IsDigit(sb[0])) sb.Insert(0, '_');
        return sb.ToString();
    }
}

// ── Minimal sfnt (TrueType/OpenType) reader: table directory, cmap (fmt 4 & 12), post v2.0 ──
sealed class SfntFont
{
    readonly byte[] _d;
    readonly Dictionary<string, (int Offset, int Length)> _tables;

    SfntFont(byte[] d, Dictionary<string, (int, int)> tables) { _d = d; _tables = tables; }

    public static SfntFont Parse(byte[] d)
    {
        if (d.Length < 12) throw new InvalidDataException("file too small");
        var tag = BinaryPrimitives.ReadUInt32BigEndian(d);
        if (tag == 0x74746366) // 'ttcf' — font collection
            throw new InvalidDataException(".ttc collections are unsupported; extract a single face first");
        // Accept 0x00010000 (TrueType), 'OTTO', 'true', 'typ1'.
        if (tag is not (0x00010000 or 0x4F54544F or 0x74727565 or 0x74797031))
            throw new InvalidDataException($"unknown sfnt version 0x{tag:X8}");

        int numTables = BinaryPrimitives.ReadUInt16BigEndian(d.AsSpan(4));
        var tables = new Dictionary<string, (int, int)>(numTables, StringComparer.Ordinal);
        var p = 12;
        for (var i = 0; i < numTables; i++, p += 16)
        {
            if (p + 16 > d.Length) throw new InvalidDataException("truncated table directory");
            var name = Encoding.ASCII.GetString(d, p, 4);
            var off = (int)BinaryPrimitives.ReadUInt32BigEndian(d.AsSpan(p + 8));
            var len = (int)BinaryPrimitives.ReadUInt32BigEndian(d.AsSpan(p + 12));
            tables[name] = (off, len);
        }
        return new SfntFont(d, tables);
    }

    static ushort U16(byte[] d, int o) => BinaryPrimitives.ReadUInt16BigEndian(d.AsSpan(o));
    static uint U32(byte[] d, int o) => BinaryPrimitives.ReadUInt32BigEndian(d.AsSpan(o));

    // codepoint → glyph id, from the best available Unicode cmap subtable (format 12 preferred).
    public Dictionary<int, int> ReadCmap()
    {
        var map = new Dictionary<int, int>();
        if (!_tables.TryGetValue("cmap", out var t)) throw new InvalidDataException("no cmap table");
        var b = t.Offset;
        int n = U16(_d, b + 2);

        int best = -1, bestScore = -1;
        for (var i = 0; i < n; i++)
        {
            var rec = b + 4 + i * 8;
            int plat = U16(_d, rec), enc = U16(_d, rec + 2);
            var sub = b + (int)U32(_d, rec + 4);
            int fmt = U16(_d, sub);
            var unicode = plat == 0 || (plat == 3 && enc is 1 or 10);
            if (!unicode || fmt is not (4 or 12)) continue;
            var score = (fmt == 12 ? 100 : 50) + (plat == 3 ? 1 : 0);
            if (score > bestScore) { bestScore = score; best = sub; }
        }
        if (best < 0) throw new InvalidDataException("no supported Unicode cmap subtable (format 4/12)");

        if (U16(_d, best) == 12) ReadCmap12(best, map);
        else ReadCmap4(best, map);
        return map;
    }

    void ReadCmap12(int b, Dictionary<int, int> map)
    {
        var groups = (int)U32(_d, b + 12);
        var g = b + 16;
        for (var i = 0; i < groups; i++, g += 12)
        {
            var start = (int)U32(_d, g);
            var end = (int)U32(_d, g + 4);
            var startGid = (int)U32(_d, g + 8);
            for (var cp = start; cp <= end; cp++)
                map[cp] = startGid + (cp - start);
        }
    }

    void ReadCmap4(int b, Dictionary<int, int> map)
    {
        int segX2 = U16(_d, b + 6), segs = segX2 / 2;
        var endO = b + 14;
        var startO = endO + segX2 + 2;
        var deltaO = startO + segX2;
        var rangeO = deltaO + segX2;
        for (var i = 0; i < segs; i++)
        {
            int end = U16(_d, endO + i * 2), start = U16(_d, startO + i * 2);
            short delta = (short)U16(_d, deltaO + i * 2);
            int range = U16(_d, rangeO + i * 2);
            if (start == 0xFFFF) continue;
            for (var cp = start; cp <= end; cp++)
            {
                int gid;
                if (range == 0) gid = (cp + delta) & 0xFFFF;
                else
                {
                    var addr = rangeO + i * 2 + range + (cp - start) * 2;
                    if (addr + 2 > _d.Length) continue;
                    gid = U16(_d, addr);
                    if (gid != 0) gid = (gid + delta) & 0xFFFF;
                }
                if (gid != 0) map[cp] = gid;
            }
        }
    }

    // glyph id → name, from a post v2.0 table. Empty for post 1.0/3.0/etc.
    public Dictionary<int, string> ReadPostNames()
    {
        var names = new Dictionary<int, string>();
        if (!_tables.TryGetValue("post", out var t)) return names;
        var b = t.Offset;
        if (U32(_d, b) != 0x00020000) return names;

        int numGlyphs = U16(_d, b + 32);
        var idxO = b + 34;
        var stringsO = idxO + numGlyphs * 2;

        // Custom Pascal-string names (for indices ≥ 258) follow the index array, in order.
        var custom = new List<string>();
        var p = stringsO;
        var end = t.Offset + t.Length;
        while (p < end && p < _d.Length)
        {
            int len = _d[p++];
            if (p + len > _d.Length) break;
            custom.Add(Encoding.ASCII.GetString(_d, p, len));
            p += len;
        }

        for (var g = 0; g < numGlyphs; g++)
        {
            int idx = U16(_d, idxO + g * 2);
            string? name =
                idx < 258 ? MacGlyphNames.Standard[idx]
                : (idx - 258 < custom.Count ? custom[idx - 258] : null);
            if (!string.IsNullOrEmpty(name) && name != ".notdef")
                names[g] = name;
        }
        return names;
    }
}

static class MacGlyphNames
{
    // The 258 standard Macintosh glyph names (indices 0–257 in a post v2.0 table).
    public static readonly string[] Standard = (
        ".notdef .null nonmarkingreturn space exclam quotedbl numbersign dollar percent ampersand " +
        "quotesingle parenleft parenright asterisk plus comma hyphen period slash zero one two three four " +
        "five six seven eight nine colon semicolon less equal greater question at A B C D E F G H I J K L M " +
        "N O P Q R S T U V W X Y Z bracketleft backslash bracketright asciicircum underscore grave a b c d e " +
        "f g h i j k l m n o p q r s t u v w x y z braceleft bar braceright asciitilde Adieresis Aring " +
        "Ccedilla Eacute Ntilde Odieresis Udieresis aacute agrave acircumflex adieresis atilde aring ccedilla " +
        "eacute egrave ecircumflex edieresis iacute igrave icircumflex idieresis ntilde oacute ograve " +
        "ocircumflex odieresis otilde uacute ugrave ucircumflex udieresis dagger degree cent sterling section " +
        "bullet paragraph germandbls registered copyright trademark acute dieresis notequal AE Oslash infinity " +
        "plusminus lessequal greaterequal yen mu partialdiff summation product pi integral ordfeminine " +
        "ordmasculine Omega ae oslash questiondown exclamdown logicalnot radical florin approxequal Delta " +
        "guillemotleft guillemotright ellipsis nonbreakingspace Agrave Atilde Otilde OE oe endash emdash " +
        "quotedblleft quotedblright quoteleft quoteright divide lozenge ydieresis Ydieresis fraction currency " +
        "guilsinglleft guilsinglright fi fl daggerdbl periodcentered quotesinglbase quotedblbase perthousand " +
        "Acircumflex Ecircumflex Aacute Edieresis Egrave Iacute Icircumflex Idieresis Igrave Oacute Ocircumflex " +
        "apple Ograve Uacute Ucircumflex Ugrave dotlessi circumflex tilde macron breve dotaccent ring cedilla " +
        "hungarumlaut ogonek caron Lslash lslash Scaron scaron Zcaron zcaron brokenbar Eth eth Yacute yacute " +
        "Thorn thorn minus multiply onesuperior twosuperior threesuperior onehalf onequarter threequarters " +
        "franc Gbreve gbreve Idotaccent Scedilla scedilla Cacute cacute Ccaron ccaron dcroat"
    ).Split(' ', StringSplitOptions.RemoveEmptyEntries);
}
