<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Zigote.Network</RootNamespace>
        <AssemblyName>Zigote.Network</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Zigote.Core\Zigote.Core.csproj"/>
    </ItemGroup>
</Project>
