<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Zigote.Render2D</RootNamespace>
        <AssemblyName>Zigote.Render2D</AssemblyName>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Zigote.Core\Zigote.Core.csproj"/>
    </ItemGroup>
</Project>
